---
- name: Installing and Running apache
  hosts: localhost
  become_method: sudo
  become: yes
  tasks:
  - name: Install apache
    yum:
      name: httpd
      state: present
  
  - name: Start httpd service
    service:
      name: httpd
      state: started
